version: '3.8'

services:
  # Self-hosted ChromaDB with persistent storage
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma_data
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    restart: unless-stopped

  # RAG App with FastAPI + Streamlit
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    volumes:
      - ./pdfs:/app/pdfs  # Mount PDFs locally
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - chroma
    restart: unless-stopped

volumes:
  chroma_data:  # Persistent storage for embeddings